src/main/resources/logback-spring.xml

logback-spring file create 
콘솔 로그 기록하는 방법

create logback file

---

src/main/java/org/cnu/realcoding/exception/DogsNotFoundException.java

And DogsNotFoundException Class added.

exception package added.

---

src/main/java/org/cnu/realcoding/controller/DogController.java
src/main/java/org/cnu/realcoding/service/DogManagementService.java

controller -> DogController Class added.
service -> DogManagementService Class added.

controller, service package added.

---

pom.xml

connect mongoDB

---

src/main/java/org/cnu/realcoding/controller/DogController.java
src/main/java/org/cnu/realcoding/domain/Dog.java
src/main/java/org/cnu/realcoding/repository/DogRepository.java
src/main/java/org/cnu/realcoding/service/DogManagementService.java

insertDog init

---

src/main/java/org/cnu/realcoding/controller/DogController.java
src/main/java/org/cnu/realcoding/exception/DogsNotFoundException.java
src/main/java/org/cnu/realcoding/repository/DogRepository.java
src/main/java/org/cnu/realcoding/service/DogManagementService.java

add find by name, ownerName, ownerPhoneName
find함수를 사용해서 list로 반환하여 출력

add find by name, ownerName, ownerPhoneName

---

src/main/java/org/cnu/realcoding/controller/DogController.java
src/main/java/org/cnu/realcoding/repository/DogRepository.java
src/main/java/org/cnu/realcoding/service/DogManagementService.java

return type changed List to Dog

Find dog by three param

---

src/main/java/org/cnu/realcoding/controller/DogController.java
src/main/java/org/cnu/realcoding/repository/DogRepository.java
src/main/java/org/cnu/realcoding/service/DogManagementService.java

update only kind API create
수정 파트중에 kind만 수정하는 API구현. 
kind를 수정하기위하여 원하는 강아지를 찾기 위해 name, ownerName, ownerPhoneNumber을 파라미터로 받아 먼저 강아지를 찾은다음에 그 강아지의 kind를 수정하게 했습니다. 
먼저 세 정보로 강아지를 찾아 일치하는 강아지가 없으면 404를 뜨게 했습니다.

update only kind API create

---

src/main/java/org/cnu/realcoding/service/DogManagementService.java

this.getDogsByNameAndOwnerNameAndOwnerPhoneNumber(name,ownerName);
to
this.getDogByNameAndOwnerNameAndOwnerPhoneNumber(name,ownerName,ownerPhoneNumber);

Typo fixed at DogManagementService Class

---

src/main/java/org/cnu/realcoding/controller/DogController.java
src/main/java/org/cnu/realcoding/repository/DogRepository.java
src/main/java/org/cnu/realcoding/service/DogManagementService.java

DogController Class,
DogRepository Class,
DogManagementService Class changed.

통째로 덮어쓰는 API 구현

---

src/main/java/org/cnu/realcoding/controller/DogController.java
src/main/java/org/cnu/realcoding/repository/DogRepository.java
src/main/java/org/cnu/realcoding/service/DogManagementService.java

write addMedicalRecord
remove updateToKind

addMedicalRecord and remove updateToKind

---

src/main/java/org/cnu/realcoding/controller/DogController.java
src/main/java/org/cnu/realcoding/repository/DogRepository.java
src/main/java/org/cnu/realcoding/service/DogManagementService.java

find메소드의 Mapping을 pacth로 바꿨습니다.

modify kindFind

---

src/main/java/org/cnu/realcoding/controller/DogController.java
src/main/java/org/cnu/realcoding/repository/DogRepository.java
src/main/java/org/cnu/realcoding/service/DogManagementService.java

Modify addMedicalRecord

---

src/main/java/org/cnu/realcoding/repository/DogRepository.java
src/main/java/org/cnu/realcoding/service/DogManagementService.java

merge 하는 과정에서 kind를 바꾸는 부분이 없어져서 수정했습니다.

conflict resolve

---

src/main/java/org/cnu/realcoding/repository/DogRepository.java
src/main/java/org/cnu/realcoding/service/DogManagementService.java

Modify findKind 를 merge하면서 생긴 충돌을 해결했습니다.

Modify findKind

---

src/main/java/org/cnu/realcoding/repository/DogRepository.java

UpdateKind overlapping

---

src/main/java/org/cnu/realcoding/controller/DogController.java
src/main/java/org/cnu/realcoding/repository/DogRepository.java
src/main/java/org/cnu/realcoding/service/DogManagementService.java

진료기록 list를 추가하는 과정에서 추가가 되지않아 수정하였습니다.
(string을 받아 list에 추가하여야하는데 list안에 list를 추가하도록 하여서 list 두번째요소부터 get이 되지 않는 것이었음)

Final modification

---

src/main/java/org/cnu/realcoding/exception/AccessMedicalRecordException.java

기존의 존재하던 기록에 접근해 수정하려고 할때 무조건적으로 XXX http status를 반환하는 exception처리

add Exception

---

src/main/java/org/cnu/realcoding/controller/DogController.java
src/main/java/org/cnu/realcoding/repository/DogRepository.java
src/main/java/org/cnu/realcoding/service/DogManagementService.java

Deleted unused import statement
Indented some codes
Reduced some space lines
from DogController, DogRepository, DogManagementService

Refatoring

---

src/main/java/org/cnu/realcoding/exception/AccessMedicalRecordException.java

Error due to the different name of class, file name

Fixed Exception Error.
